trigger:
  batch: true
  branches:
    include:
      - "*"

  paths:
    include:
    - "*"
    exclude:
    - README.md

pr: none

pool:
  name: "DAS - Continuous Integration"
  demands:
  - Agent.OS -equals Windows

variables:
- group: Release Management Resources

stages:
- stage: Build
  jobs:
  - template: /pipeline-templates/job/build.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM
