trigger:
  batch: true
  branches:
    include:
      - "*"

  paths:
    include:
    - "*"
    exclude:
    - README.md

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  DockerRegistryServiceConnection: 'Apprenticeships DevOps Docker Hub'
  ImageRepository: apprenticeshipsdevops/das-logstash-exporter
  DockerfilePath: '**/Dockerfile'

stages:
- stage: Build
  jobs:
  - template: /pipeline-templates/job/code-build.yml
    parameters:
      ImageRepository: $(ImageRepository)
      DockerFilePath: $(DockerfilePath)
      DockerRegistryServiceConnection: $(DockerRegistryServiceConnection)
