resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.18
    endpoint: SFA
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.4.0
    endpoint: SFA

trigger:
  batch: true
  branches:
    include:
      - "*"

  paths:
    include:
    - "*"
    exclude:
    - README.md

pr: none

variables:
- name: KubectlVersion
  value: 1.18.8
- group: Release Management Resources

stages:
  - template: /pipeline-templates/stage/build.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM

  - stage: DeployTo_DEV
    displayName: Deploy To Dev
    variables:
    - group: Dev Management Resources
    jobs:
    - template: /pipeline-templates/job/deploy.yml
      parameters:
        Environment: DEV
        ServiceConnection: SFA-DAS-DevTest-ARM
