trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'Docker Hub'
  imageRepository: chelnak/logstash_exporter
  dockerfilePath: '**/Dockerfile'
  
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: gittools.gitversion.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        configFilePath: GitVersion.yml

    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: $(dockerFilePath)
        tags: '$(Build.BuildNumber)'

    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'push'
        Dockerfile: '$(dockerFilePath)'
        tags: '$(Build.BuildNumber)'

    - task: Docker@2
      displayName: Push tagged image (latest) if master
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'push'
        Dockerfile: '$(dockerFilePath)'
        tags: 'latest'

    - task: GitHubRelease@0
      displayName: Create a GitHub GitHubRelease
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        gitHubConnection: 'chelnak'
        repositoryName: 'chelnak/logstash_exporter'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'manual'
        tag: '$(Build.BuildNumber)'