parameters:
  ServiceConnection:

jobs:
- job: Build_Image
  displayName: Build Image
  steps:
    - task: gittools.gitversion.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        configFilePath: GitVersion.yml
        updateAssemblyInfo: true

    - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
      parameters:
        ContainerRegistryName: $(PublicAcrName)
        ServiceConnection: ${{ parameters.ServiceConnection }}
        ImageName: das-logstash-exporter
