parameters:
  ImageRepository:
  DockerFilePath:
  DockerRegistryServiceConnection:

jobs:
- job: Build
  displayName: Build
  steps:

  - task: gittools.gitversion.gitversion-task.GitVersion@5
    displayName: GitVersion
    inputs:
      configFilePath: GitVersion.yml

  - bash: echo "##vso[build.updatebuildnumber]${BUILD_BUILDNUMBER}-prerelease"
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: 'Set non master build number'

  - bash: echo $BUILD_BUILDNUMBER > VERSION
    displayName: "Set build number"

  - task: Docker@2
    inputs:
      repository: ${{ parameters.ImageRepository }}
      command: 'build'
      Dockerfile: ${{ parameters.DockerFilePath }}
      tags: '$(Build.BuildNumber)'

  - task: Docker@2
    displayName: "Push tagged image [Build.BuildNumber]"
    inputs:
      containerRegistry: ${{ parameters.DockerRegistryServiceConnection }}
      repository: ${{ parameters.ImageRepository }}
      command: 'push'
      Dockerfile: ${{ parameters.DockerFilePath }}
      tags: '$(Build.BuildNumber)'
