apiVersion: v1
kind: Service
metadata:
  name: das-logstash-exporter
  labels:
    app: das-logstash-exporter
spec:
  ports:
  - name: ls-exporter
    port: 9198
    protocol: TCP
  selector:
    app: das-logstash-exporter

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: das-logstash-exporter
  namespace: monitoring
spec:
  serviceName: logstash-exporter
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: das-logstash-exporter
  template:
    metadata:
      labels:
        app: das-logstash-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9198'
    spec:
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - logstash01
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - das-logstash-exporter
                topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - name: das-logstash-exporter
        image: __PublicAcrName__.azurecr.io/das-logstash-exporter:0.1.20-DASD-8842-Logstash-Exporter-Setup.17
        command: ["/bin/sh", "-c"]
        args:
          - >-
            exec /logstash_exporter --logstash.endpoint=http://logstash-dta-logstash-dta-headless:9600 --web.listen-address=:9198
        resources:
          requests:
            memory: 256Mi
        ports:
        - containerPort: 9198
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9198
          periodSeconds: 15
          timeoutSeconds: 60
          failureThreshold: 8
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9198
          periodSeconds: 15
          timeoutSeconds: 60
          failureThreshold: 8
          successThreshold: 1

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: das-logstash-exporter
  namespace: monitoring
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 10s
    scrapeTimeout: 10s
    port: ls-exporter
    path: /metrics
  jobLabel: das-logstash-exporter
  selector:
    matchLabels:
      app: das-logstash-exporter
      release: das-logstash-exporter
  namespaceSelector:
    matchNames:
      - monitoring
